project:
  type: website
  output-dir: docs
  resources:
    - custom-hero.css
    - custom-scroll.js
    - styles.css
    - material/
  
  render:
    - index.qmd
    - qmd/**/*.qmd  # recursively render all .qmd files

    # - "!qmd/chapter_1/ch1_1.qmd"  # Exclude this specific file
    # - "!qmd/chapter_1/ch1_2.qmd"  # Exclude this specific file
    # - "!qmd/chapter_1/ch1_4.qmd"  # Exclude this specific file
    # - "!qmd/chapter_1/ch1_5.qmd"  # Exclude this specific file
    # - "!qmd/chapter_1/ch1_6.qmd"  # Exclude this specific file
    # - "!qmd/chapter_1/ch1_7.qmd"  # Exclude this specific file
    # - "!qmd/chapter_1/ch1_8.qmd"  # Exclude this specific file

    
execute:
  freeze: auto

website:
  title: "Movement Ecology - Shorebirds"

  navbar:
    background: primary
    search: true

    logo: logo.png
        
    right:     
      - text: "PhD Project"
        href: qmd/myphd.qmd
        
      - sidebar:chapter1
      - sidebar:chapter2
      - sidebar:chapter3
      - sidebar:chapter4
      - sidebar:chapter5
      - sidebar:reports

      - text: "Get in touch"
        href: qmd/contact.qmd
        
  # Define multiple sidebars as a LIST
  sidebar:
    - id: chapter1
      title: "Chapter 1"
      style: docked
      background: light
      collapse-level: 3
      contents:
        - section: "Data"
          contents:
            - qmd/chapter_1/ch1_1.qmd # Load and Format
            - qmd/chapter_1/ch1_2.qmd # Explore
            - qmd/chapter_1/ch1_3.qmd # Styles
            
        - section: "Motus array"
          contents:
            - qmd/chapter_1/ch1_4.qmd # Location and History
            - qmd/chapter_1/ch1_5.qmd # Survey effort
            
        - section: "Analysis"
          contents:
            - qmd/chapter_1/ch1_6.qmd # Estuary Usage
            - qmd/chapter_1/ch1_7.qmd # Station Usage rate
            - qmd/chapter_1/ch1_8.qmd # Signal strength
            
        - section: "Results"
          contents:
            - qmd/chapter_1/ch1_9.qmd # Results

    - id: chapter2
      title: "Chapter 2"
      style: docked
      background: light
      collapse-level: 3
      contents:
        - href: qmd/chapter_2/ch2_1.qmd

    - id: chapter3
      title: "Chapter 3"
      style: docked
      background: light
      collapse-level: 3
      contents:
        - href: qmd/chapter_3/ch3_1.qmd

    - id: chapter4
      title: "Chapter 4"
      style: docked
      background: light
      collapse-level: 3
      contents:
        - href: qmd/chapter_4/ch4_1.qmd

    - id: chapter5
      title: "Chapter 5"
      style: docked
      background: light
      collapse-level: 3
      contents:
        - href: qmd/chapter_5/ch5_1.qmd
        
    - id: reports
      title: "Publications"
      style: docked
      background: light
      collapse-level: 3
      contents:
        - qmd/reports/pub_1.qmd  # us
        - qmd/reports/pub_2.qmd  # ethics + grant reports
        - qmd/reports/pub_3.qmd  # conference + papers
        - qmd/reports/pub_4.qmd  # milestones
        - qmd/reports/pub_5.qmd  # awards

            
format:
  html:
    theme: [cosmo, brand]
    css: styles.css
    toc: true
    include-after-body: _footer.html


editor: visual